// system_audio_clock.v

// This file was auto-generated from altera_up_avalon_sys_sdram_pll_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module system_audio_clock (
		input  wire  ref_clk_clk,        //      ref_clk.clk
		input  wire  ref_reset_reset,    //    ref_reset.reset
		output wire  sys_clk_clk,        //      sys_clk.clk
		output wire  sdram_clk_clk,      //    sdram_clk.clk
		output wire  reset_source_reset  // reset_source.reset
	);

	wire    sys_pll_locked_export; // sys_pll:locked -> reset_from_locked:locked

	system_audio_clock_sys_pll sys_pll (
		.refclk   (ref_clk_clk),           //  refclk.clk
		.rst      (ref_reset_reset),       //   reset.reset
		.outclk_0 (sys_clk_clk),           // outclk0.clk
		.outclk_1 (sdram_clk_clk),         // outclk1.clk
		.locked   (sys_pll_locked_export)  //  locked.export
	);

	altera_up_avalon_reset_from_locked_signal reset_from_locked (
		.reset  (reset_source_reset),    // reset_source.reset
		.locked (sys_pll_locked_export)  //       locked.export
	);

endmodule
